spring.application.name=EstoqueSaepAPI

spring.datasource.url=jdbc:mysql://172.16.0.30/ldb_estoque?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=ldb
spring.datasource.password=gmSenai
spring.jpa.show-sql=True